

- hosts: local

  tasks:
    # NOTE: Everything is installed with
    #   Python 2. This is because the
    #   Ansible mapping to Python 3 is
    #   not yet supported.

    # ---------------------------
    # Install Python 2 and verify
    # ---------------------------
    - name: Install Python 2
      apt:
        pkg: python 
        state: installed
      become: True
      become_method: sudo

    # -------------------------------
    # Install Python 2 dev and verify
    # -------------------------------
    - name: Install Python 2 dev
      apt:
        pkg: python-dev
        state: installed
      become: True
      become_method: sudo

    # -------------------------------
    # Install Python 2 pip and verify
    # -------------------------------
    - name: Install Python 2 pip
      apt:
        pkg: python-pip
        state: installed
      become: True
      become_method: sudo

    # --------------------------------------
    # Install Python 2 virtualenv and verify
    # --------------------------------------
    - name: Install Python 2 virtualenv
      apt:
        pkg: python-virtualenv
        state: installed
      become: True
      become_method: sudo

    # ---------------------------
    # Install Python 2 Setuptools
    # ---------------------------
    - name: Install Python Pip Setuptools Package
      pip:
        name: setuptools
        state: latest
      become: True
      become_method: sudo


