

- hosts: local

  tasks:
    # NOTE: Everything is installed with
    #   Python 2. This is because the
    #   Ansible mapping to Python 3 is
    #   not yet supported.

    # -------------------
    # Install Pip Ansible
    # -------------------
    - name: Install Python 2 Pip Ansible Package
      pip:
        name: ansible
        state: latest
      become: True
      become_method: sudo
    
    # ----------------
    # Install Pip Boto
    # ----------------
    - name: Install Python 2 Pip Boto Package
      pip:
        name: boto
        state: latest
      become: True
      become_method: sudo

    # -----------------
    # Install Pip Boto3
    # -----------------
    - name: Install Python 2 Pip Boto 3 Package
      pip:
        name: boto3
        state: latest
      become: True
      become_method: sudo

    # ----------------------------------------
    # Install AWS CLI (Command Line Interface)
    # ----------------------------------------
    - name: Install Python 2 Pip AWS CLI Package
      pip:
        name: awscli
        state: latest
      become: True
      become_method: sudo



